version: "3.9"

services:
  postgres-sample:
    image: postgres:17
    container_name: postgres-sample
    environment:
      POSTGRES_PASSWORD: pass_nerdery
      POSTGRES_USER: postgres
      POSTGRES_DB: nerdery_db
    restart: always
    ports:
      - 5432:5432
      # add your port in case you have 5432 in use e.g 5434:5432 for 5434
    volumes:
      - ./init.db:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
